# armhf
FROM armv7/armhf-ubuntu:16.04
MAINTAINER Taka Wang <taka@cmwang.net>

ENV CONF_WEB "/etc/mb-web"
ENV EP_BACKEND "consul.cmwang.net:8500"
ENV ZMQ_VERSION 3.2.5

# add binary
ADD libzmq.so.3.0.0 /usr/lib/
ADD libzmq.so.3 /usr/lib/
ADD web /
ADD config.toml ${CONF_WEB}/

ENTRYPOINT /web

EXPOSE 8080